CREATE TABLE info (
  restaurant_id INT,
  name TEXT,
  latitude  TEXT,
  longitude TEXT,
  map TEXT,
  dining_style TEXT,
  cuisines TEXT,
  hours_of_operations jsonb,
  cross_street TEXT,
  dress_code TEXT,
  price_range TEXT,
  payment_options jsonb,
  phone_number TEXT,
  website TEXT,
  catering jsonb,
  public_transit TEXT,
  executive_chef TEXT,
  additional jsonb,
  special_events TEXT,
  promotions TEXT,
  rating TEXT,
  reviews TEXT,
  top_tags TEXT [],
  description TEXT,
  neighborhood TEXT,
  parking TEXt
);